### PR TITLE
R6 rebased

### PR DESCRIPTION
**Pull request by tverbele**
Hi all, 

I rebased the R6 branch on the latest master. 

@JochenHiller : could you run the R6 CTK to check which are still open issues?

### CODE REVIEW

**Comment by svilenvul** [comment]
Hello, is there any update on the R6 suppport?

**Comment by rellermeyer** [comment]
> Hello, is there any update on the R6 support?

We are planning to release 5.1 on Nov. 8th and will then shift focus to the R6 release.

**Comment by svilenvul** [comment]
Thank you for the quick reply.

**Comment by tverbele** [comment]
@JochenHiller @rellermeyer I updated the r6 branch rebase so we can merge it into master. Builds on my machine. Should run the CTK though and list remaining TODOs to make it compatible.

**Pull request merged**
